package calculadora;

/**
 *
 * @author Mauro Federico Lopez
 */
public class CalculadoraUI extends javax.swing.JFrame {

    private Float primerNum, segundoNum, resultadoNum;
    private Boolean sumaClick, restaClick, productoClick, divisionClick;

    /**
     * Creates new form Calculadora
     */
    public CalculadoraUI() {
        initComponents();
        sumaClick = false;
        restaClick = false;
        productoClick = false;
        divisionClick = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpBotones = new javax.swing.JPanel();
        jbNueve = new javax.swing.JButton();
        jbOcho = new javax.swing.JButton();
        jbSiete = new javax.swing.JButton();
        jbSeis = new javax.swing.JButton();
        jbCinco = new javax.swing.JButton();
        jbCuatro = new javax.swing.JButton();
        jbTres = new javax.swing.JButton();
        jbDos = new javax.swing.JButton();
        jbUno = new javax.swing.JButton();
        jbCero = new javax.swing.JButton();
        jbC = new javax.swing.JButton();
        jbComa = new javax.swing.JButton();
        jbDivision = new javax.swing.JButton();
        jbProducto = new javax.swing.JButton();
        jbResta = new javax.swing.JButton();
        jbSuma = new javax.swing.JButton();
        jbIgual = new javax.swing.JButton();
        jlDisplay = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbNueve.setText("9");
        jbNueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNueveActionPerformed(evt);
            }
        });

        jbOcho.setText("8");
        jbOcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOchoActionPerformed(evt);
            }
        });

        jbSiete.setText("7");
        jbSiete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSieteActionPerformed(evt);
            }
        });

        jbSeis.setText("6");
        jbSeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSeisActionPerformed(evt);
            }
        });

        jbCinco.setText("5");
        jbCinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCincoActionPerformed(evt);
            }
        });

        jbCuatro.setText("4");
        jbCuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCuatroActionPerformed(evt);
            }
        });

        jbTres.setText("3");
        jbTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbTresActionPerformed(evt);
            }
        });

        jbDos.setText("2");
        jbDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDosActionPerformed(evt);
            }
        });

        jbUno.setText("1");
        jbUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUnoActionPerformed(evt);
            }
        });

        jbCero.setText("0");
        jbCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCeroActionPerformed(evt);
            }
        });

        jbC.setText("C");
        jbC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCActionPerformed(evt);
            }
        });

        jbComa.setText(".");
        jbComa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbComaActionPerformed(evt);
            }
        });

        jbDivision.setText("/");
        jbDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDivisionActionPerformed(evt);
            }
        });

        jbProducto.setText("*");
        jbProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProductoActionPerformed(evt);
            }
        });

        jbResta.setText("-");
        jbResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRestaActionPerformed(evt);
            }
        });

        jbSuma.setText("+");
        jbSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSumaActionPerformed(evt);
            }
        });

        jbIgual.setText("=");
        jbIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbIgualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpBotonesLayout = new javax.swing.GroupLayout(jpBotones);
        jpBotones.setLayout(jpBotonesLayout);
        jpBotonesLayout.setHorizontalGroup(
            jpBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpBotonesLayout.createSequentialGroup()
                        .addComponent(jbSiete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbOcho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbNueve))
                    .addGroup(jpBotonesLayout.createSequentialGroup()
                        .addComponent(jbCuatro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbCinco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbSeis))
                    .addGroup(jpBotonesLayout.createSequentialGroup()
                        .addComponent(jbUno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbDos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbTres))
                    .addGroup(jpBotonesLayout.createSequentialGroup()
                        .addComponent(jbComa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbCero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbC)))
                .addGroup(jpBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpBotonesLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jpBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbSuma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbResta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jpBotonesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbDivision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpBotonesLayout.setVerticalGroup(
            jpBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpBotonesLayout.createSequentialGroup()
                            .addComponent(jbSuma)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbResta)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbProducto)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jbDivision))
                        .addGroup(jpBotonesLayout.createSequentialGroup()
                            .addGroup(jpBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jbSiete)
                                .addComponent(jbOcho)
                                .addComponent(jbNueve))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jpBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jbCuatro)
                                .addComponent(jbCinco)
                                .addComponent(jbSeis))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jpBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jbUno)
                                .addComponent(jbDos)
                                .addComponent(jbTres))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jpBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jbComa)
                                .addComponent(jbCero)
                                .addComponent(jbC)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlDisplay.setBackground(new java.awt.Color(255, 255, 255));
        jlDisplay.setFont(new java.awt.Font("Arial", 0, 32)); // NOI18N
        jlDisplay.setForeground(new java.awt.Color(51, 51, 51));
        jlDisplay.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlDisplay.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jpBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSieteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSieteActionPerformed
        if (jlDisplay.getText().equals("0"))
            jlDisplay.setText(jbSiete.getText());
        else
            jlDisplay.setText(jlDisplay.getText()+jbSiete.getText());
    }//GEN-LAST:event_jbSieteActionPerformed

    private void jbOchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOchoActionPerformed
        if (jlDisplay.getText().equals("0"))
            jlDisplay.setText(jbOcho.getText());
        else
            jlDisplay.setText(jlDisplay.getText()+jbOcho.getText());
    }//GEN-LAST:event_jbOchoActionPerformed

    private void jbNueveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNueveActionPerformed
        if (jlDisplay.getText().equals("0"))
            jlDisplay.setText(jbNueve.getText());
        else
            jlDisplay.setText(jlDisplay.getText()+jbNueve.getText());
    }//GEN-LAST:event_jbNueveActionPerformed

    private void jbCuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCuatroActionPerformed
        if (jlDisplay.getText().equals("0"))
            jlDisplay.setText(jbCuatro.getText());
        else
            jlDisplay.setText(jlDisplay.getText()+jbCuatro.getText());
    }//GEN-LAST:event_jbCuatroActionPerformed

    private void jbCincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCincoActionPerformed
        if (jlDisplay.getText().equals("0"))
            jlDisplay.setText(jbCinco.getText());
        else
            jlDisplay.setText(jlDisplay.getText()+jbCinco.getText());
    }//GEN-LAST:event_jbCincoActionPerformed

    private void jbSeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSeisActionPerformed
        if (jlDisplay.getText().equals("0"))
            jlDisplay.setText(jbSeis.getText());
        else
            jlDisplay.setText(jlDisplay.getText()+jbSeis.getText());
    }//GEN-LAST:event_jbSeisActionPerformed

    private void jbUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUnoActionPerformed
        if (jlDisplay.getText().equals("0"))
            jlDisplay.setText(jbUno.getText());
        else
            jlDisplay.setText(jlDisplay.getText()+jbUno.getText());
    }//GEN-LAST:event_jbUnoActionPerformed

    private void jbDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDosActionPerformed
        if (jlDisplay.getText().equals("0"))
            jlDisplay.setText(jbDos.getText());
        else
            jlDisplay.setText(jlDisplay.getText()+jbDos.getText());
    }//GEN-LAST:event_jbDosActionPerformed

    private void jbTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbTresActionPerformed
        if (jlDisplay.getText().equals("0"))
            jlDisplay.setText(jbTres.getText());
        else
            jlDisplay.setText(jlDisplay.getText()+jbTres.getText());
    }//GEN-LAST:event_jbTresActionPerformed

    private void jbCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCeroActionPerformed
        if (jlDisplay.getText().equals("0"))
            jlDisplay.setText(jbCero.getText());
        else
            jlDisplay.setText(jlDisplay.getText()+jbCero.getText());
    }//GEN-LAST:event_jbCeroActionPerformed

    private void jbComaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbComaActionPerformed
        jlDisplay.setText(jlDisplay.getText()+jbComa.getText());
    }//GEN-LAST:event_jbComaActionPerformed

    private void jbSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSumaActionPerformed
        primerNum = Float.parseFloat(jlDisplay.getText());
        jlDisplay.setText("0");
        sumaClick = true;
        restaClick = false;
        productoClick = false;
        divisionClick = false;
    }//GEN-LAST:event_jbSumaActionPerformed

    private void jbRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRestaActionPerformed
        primerNum = Float.parseFloat(jlDisplay.getText());
        jlDisplay.setText("0");
        sumaClick = false;
        restaClick = true;
        productoClick = false;
        divisionClick = false;
    }//GEN-LAST:event_jbRestaActionPerformed

    private void jbProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProductoActionPerformed
        primerNum = Float.parseFloat(jlDisplay.getText());
        jlDisplay.setText("0");
        sumaClick = false;
        restaClick = false;
        productoClick = true;
        divisionClick = false;
    }//GEN-LAST:event_jbProductoActionPerformed

    private void jbDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDivisionActionPerformed
        primerNum = Float.parseFloat(jlDisplay.getText());
        jlDisplay.setText("0");
        sumaClick = false;
        restaClick = false;
        productoClick = false;
        divisionClick = true;
    }//GEN-LAST:event_jbDivisionActionPerformed

    private void jbCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCActionPerformed
        jlDisplay.setText("0");
        sumaClick = false;
        restaClick = false;
        productoClick = false;
        divisionClick = false;
    }//GEN-LAST:event_jbCActionPerformed

    private void jbIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbIgualActionPerformed
        segundoNum = Float.parseFloat(jlDisplay.getText());
        if (sumaClick) {
            segundoNum = primerNum + segundoNum;
            jlDisplay.setText(String.valueOf(segundoNum));
        }
        else if (restaClick) {
                segundoNum = primerNum - segundoNum;
                jlDisplay.setText(String.valueOf(segundoNum));
        }
        else if (productoClick) {
                segundoNum = primerNum * segundoNum;
                jlDisplay.setText(String.valueOf(segundoNum));
        }
        else if (divisionClick) {
                if (primerNum != 0) {
                    segundoNum = primerNum / segundoNum;
                    jlDisplay.setText(String.valueOf(segundoNum));
                }
        }

        // sumaClick = false;
        // restaClick = false;
        // productoClick = false;
        // divisionClick = false;
    }//GEN-LAST:event_jbIgualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CalculadoraUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbC;
    private javax.swing.JButton jbCero;
    private javax.swing.JButton jbCinco;
    private javax.swing.JButton jbComa;
    private javax.swing.JButton jbCuatro;
    private javax.swing.JButton jbDivision;
    private javax.swing.JButton jbDos;
    private javax.swing.JButton jbIgual;
    private javax.swing.JButton jbNueve;
    private javax.swing.JButton jbOcho;
    private javax.swing.JButton jbProducto;
    private javax.swing.JButton jbResta;
    private javax.swing.JButton jbSeis;
    private javax.swing.JButton jbSiete;
    private javax.swing.JButton jbSuma;
    private javax.swing.JButton jbTres;
    private javax.swing.JButton jbUno;
    private javax.swing.JLabel jlDisplay;
    private javax.swing.JPanel jpBotones;
    // End of variables declaration//GEN-END:variables
}
